
services:
    mysql:
        container_name: "mysql"
        image: mysql:8.0
        volumes:
            - ./database/oai_db2.sql:/docker-entrypoint-initdb.d/oai_db.sql
            - ./healthscripts/mysql-healthcheck2.sh:/tmp/mysql-healthcheck.sh
        environment:
            - TZ=Europe/Paris
            - MYSQL_DATABASE=oai_db
            - MYSQL_USER=test
            - MYSQL_PASSWORD=test
            - MYSQL_ROOT_PASSWORD=linux
        healthcheck:
            test: /bin/bash -c "/tmp/mysql-healthcheck.sh"
            interval: 10s
            timeout: 5s
            retries: 30
        networks:
            public_net:
                ipv4_address: 192.168.70.131
    oai-nssf:
        container_name: "oai-nssf"
        image: oaisoftwarealliance/oai-nssf:develop
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./conf/slicing_base_config.yaml:/openair-nssf/etc/config.yaml
            - ./conf/nssf_slice_config.yaml:/openair-nssf/etc/nssf_slice_config.yaml
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            public_net:
                ipv4_address: 192.168.70.132
    oai_udr:
        container_name: "oai-udr"
        image: oaisoftwarealliance/oai-udr:develop
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./conf/slicing_base_config.yaml:/openair-udr/etc/config.yaml
        depends_on:
            - mysql
        networks:
            public_net:
                ipv4_address: 192.168.70.136
    oai_udm:
        container_name: "oai-udm"
        image: oaisoftwarealliance/oai-udm:develop
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./conf/slicing_base_config.yaml:/openair-udm/etc/config.yaml
        depends_on:
            - oai_udr
        networks:
            public_net:
                ipv4_address: 192.168.70.137
    oai_ausf:
        container_name: "oai-ausf"
        image: oaisoftwarealliance/oai-ausf:develop
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./conf/slicing_base_config.yaml:/openair-ausf/etc/config.yaml
        depends_on:
            - oai_udm
        networks:
            public_net:
                ipv4_address: 192.168.70.138
    oai_nrf_slice123:
        container_name: "oai-nrf-slice123"
        image: oaisoftwarealliance/oai-nrf:develop
        expose:
            - 80/tcp
            - 8080/tcp
        volumes:
            - ./conf/slicing_slice1_config.yaml:/openair-nrf/etc/config.yaml
        networks:
            public_net:
                ipv4_address: 192.168.70.130
    oai_amf:
        container_name: "oai-amf"
        image: oaisoftwarealliance/oai-amf:develop
        expose:
            - 80/tcp
            - 8080/tcp
            - 38412/sctp
        volumes:
            - ./conf/slicing_base_config.yaml:/openair-amf/etc/config.yaml
        depends_on:
            - oai_nrf_slice123
            - oai_ausf
        extra_hosts:
            - "oai-nrf:192.168.70.136"
        networks:
            public_net:
                ipv4_address: 192.168.70.100
    oai_smf_slice1:
        container_name: "oai-smf-slice1"
        image: oaisoftwarealliance/oai-smf:develop
        expose:
            - 80/tcp
            - 8080/tcp
            - 8805/udp
        volumes:
            - ./conf/slicing_slice1_config.yaml:/openair-smf/etc/config.yaml
        depends_on:
            - oai_amf
            - oai_nrf_slice123
        networks:
            public_net:
                ipv4_address: 192.168.70.251
    oai_smf_slice2:
        container_name: "oai-smf-slice2"
        image: oaisoftwarealliance/oai-smf:develop
        expose:
            - 80/tcp
            - 8080/tcp
            - 8805/udp
        volumes:
            - ./conf/slicing_slice2_config.yaml:/openair-smf/etc/config.yaml
        depends_on:
            - oai_amf
            - oai_nrf_slice123
        networks:
            public_net:
                ipv4_address: 192.168.70.252
    oai_smf_slice3:
        container_name: "oai-smf-slice3"
        image: oaisoftwarealliance/oai-smf:develop
        expose:
            - 80/tcp
            - 8080/tcp
            - 8805/udp
        volumes:
            - ./conf/slicing_slice3_config.yaml:/openair-smf/etc/config.yaml
        depends_on:
            - oai_amf
            - oai_nrf_slice123
        networks:
            public_net:
                ipv4_address: 192.168.70.253

    oai_upf_slice1:
        container_name: "oai-upf-slice1"
        image: oaisoftwarealliance/oai-upf:develop
        expose:
            - 2152/udp
            - 8805/udp
            - 8080/tcp
        volumes:
            - ./entrypoint.sh:/entrypoint.sh:ro
            - ./conf/slicing_slice1_config.yaml:/openair-upf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai_nrf_slice123
            - oai_smf_slice1
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            public_net:
                ipv4_address: 192.168.70.201
            oai-n6:
                ipv4_address: 192.168.80.201
        command: ["/bin/bash", "/entrypoint.sh"]

    oai_upf_slice2:
        container_name: "oai-upf-slice2"
        image: oaisoftwarealliance/oai-upf:develop
        expose:
            - 2152/udp
            - 8805/udp
            - 8080/tcp
        volumes:
            - ./entrypoint.sh:/entrypoint.sh:ro   
            - ./conf/slicing_slice2_config.yaml:/openair-upf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai_nrf_slice123
            - oai_smf_slice2
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            public_net:
                ipv4_address: 192.168.70.202
            oai-n6:
                ipv4_address: 192.168.80.202
        command: ["/bin/bash", "/entrypoint.sh"]

    oai_upf_slice3:
        container_name: "oai-upf-slice3"
        image: oaisoftwarealliance/oai-upf:develop
        expose:
            - 2152/udp
            - 8805/udp
            - 8080/tcp
        volumes:
            - ./entrypoint.sh:/entrypoint.sh:ro
            - ./conf/slicing_slice3_config.yaml:/openair-upf/etc/config.yaml
        environment:
            - TZ=Europe/Paris
        depends_on:
            - oai_nrf_slice123
            - oai_smf_slice3
        cap_add:
            - NET_ADMIN
            - SYS_ADMIN
        cap_drop:
            - ALL
        privileged: true
        networks:
            public_net:
                ipv4_address: 192.168.70.203
            oai-n6:
                ipv4_address: 192.168.80.203
        command: ["/bin/bash", "/entrypoint.sh"]

networks:
    oai-n6:
        driver: bridge
        name: oai-n6
        ipam:
            config:
                - subnet: 192.168.80.0/24
                  gateway: 192.168.80.1
        driver_opts:
            com.docker.network.bridge.name: "oai-n6"
    public_net:
        driver: bridge
        name: oai-cn5g
        ipam:
            config:
                - subnet: 192.168.70.0/24
                  gateway: 192.168.70.1
        driver_opts:
            com.docker.network.bridge.name: "oai-cn5g"
