services:
  iq-cubb:
    container_name: iq-cubb
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities:
                - gpu
    network_mode: "host"
    shm_size: 4096m
    privileged: true
    stdin_open: true
    tty: true
    volumes:
      - /lib/modules:/lib/modules
      - /dev/hugepages:/dev/hugepages
      - /usr/src:/usr/src
      - /var/log/aerial:/var/log/aerial
      - ../../../cmake_targets/share:/opt/cuBB/share # This is share directory
      - ./aerial_l1_entrypoint.sh:/opt/nvidia/cuBB-dev/aerial_l1_entrypoint.sh
      - ./:/opt/nvidia/cuBB-dev/cuPHY-CP/cuphycontroller/config/
      - /home/iq/cuBB-dev:/opt/nvidia/cuBB-dev/
      - /dev/mst/mt4125_pciconf0.1:/dev/mst/mt4125_pciconf0.1
    working_dir: /opt/nvidia/cuBB-dev
    userns_mode: host
    ipc: "host"
    image: nvcr.io/qhrjhjrvlsbu/aerial-cuda-accelerated-ran:24-1-cubb
    environment:
      - cuBB_SDK=/opt/nvidia/cuBB-dev
    # command: bash -c "sudo rm -rf /tmp/phy.log && sudo chmod +x /opt/nvidia/cuBB/aerial_l1_entrypoint.sh && /opt/nvidia/cuBB/aerial_l1_entrypoint.sh"
    healthcheck:
      test: ["CMD-SHELL",'grep -q "L1 is ready!" /tmp/phy.log && echo 0 || echo 1']
      interval: 20s
      timeout: 5s
      retries: 5