# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ue_service_pb2 as ue__service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ue_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UEControlServiceStub(object):
    """UE Control Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartUE = channel.unary_unary(
                '/ue_service.UEControlService/StartUE',
                request_serializer=ue__service__pb2.StartUERequest.SerializeToString,
                response_deserializer=ue__service__pb2.StartUEResponse.FromString,
                _registered_method=True)
        self.StopUE = channel.unary_unary(
                '/ue_service.UEControlService/StopUE',
                request_serializer=ue__service__pb2.StopUERequest.SerializeToString,
                response_deserializer=ue__service__pb2.StopUEResponse.FromString,
                _registered_method=True)
        self.GetStatus = channel.unary_unary(
                '/ue_service.UEControlService/GetStatus',
                request_serializer=ue__service__pb2.StatusRequest.SerializeToString,
                response_deserializer=ue__service__pb2.StatusResponse.FromString,
                _registered_method=True)
        self.ConfigureUE = channel.unary_unary(
                '/ue_service.UEControlService/ConfigureUE',
                request_serializer=ue__service__pb2.ConfigureUERequest.SerializeToString,
                response_deserializer=ue__service__pb2.ConfigureUEResponse.FromString,
                _registered_method=True)
        self.StartScanning = channel.unary_unary(
                '/ue_service.UEControlService/StartScanning',
                request_serializer=ue__service__pb2.StartScanningRequest.SerializeToString,
                response_deserializer=ue__service__pb2.StartScanningResponse.FromString,
                _registered_method=True)
        self.StopScanning = channel.unary_unary(
                '/ue_service.UEControlService/StopScanning',
                request_serializer=ue__service__pb2.StopScanningRequest.SerializeToString,
                response_deserializer=ue__service__pb2.StopScanningResponse.FromString,
                _registered_method=True)


class UEControlServiceServicer(object):
    """UE Control Service
    """

    def StartUE(self, request, context):
        """Start UE process
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopUE(self, request, context):
        """Stop UE process
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetStatus(self, request, context):
        """Get UE status
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def ConfigureUE(self, request, context):
        """Configure UE parameters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartScanning(self, request, context):
        """Start cell scanning procedure
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopScanning(self, request, context):
        """Stop cell scanning procedure
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UEControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartUE': grpc.unary_unary_rpc_method_handler(
                    servicer.StartUE,
                    request_deserializer=ue__service__pb2.StartUERequest.FromString,
                    response_serializer=ue__service__pb2.StartUEResponse.SerializeToString,
            ),
            'StopUE': grpc.unary_unary_rpc_method_handler(
                    servicer.StopUE,
                    request_deserializer=ue__service__pb2.StopUERequest.FromString,
                    response_serializer=ue__service__pb2.StopUEResponse.SerializeToString,
            ),
            'GetStatus': grpc.unary_unary_rpc_method_handler(
                    servicer.GetStatus,
                    request_deserializer=ue__service__pb2.StatusRequest.FromString,
                    response_serializer=ue__service__pb2.StatusResponse.SerializeToString,
            ),
            'ConfigureUE': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureUE,
                    request_deserializer=ue__service__pb2.ConfigureUERequest.FromString,
                    response_serializer=ue__service__pb2.ConfigureUEResponse.SerializeToString,
            ),
            'StartScanning': grpc.unary_unary_rpc_method_handler(
                    servicer.StartScanning,
                    request_deserializer=ue__service__pb2.StartScanningRequest.FromString,
                    response_serializer=ue__service__pb2.StartScanningResponse.SerializeToString,
            ),
            'StopScanning': grpc.unary_unary_rpc_method_handler(
                    servicer.StopScanning,
                    request_deserializer=ue__service__pb2.StopScanningRequest.FromString,
                    response_serializer=ue__service__pb2.StopScanningResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ue_service.UEControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ue_service.UEControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UEControlService(object):
    """UE Control Service
    """

    @staticmethod
    def StartUE(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ue_service.UEControlService/StartUE',
            ue__service__pb2.StartUERequest.SerializeToString,
            ue__service__pb2.StartUEResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopUE(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ue_service.UEControlService/StopUE',
            ue__service__pb2.StopUERequest.SerializeToString,
            ue__service__pb2.StopUEResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetStatus(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ue_service.UEControlService/GetStatus',
            ue__service__pb2.StatusRequest.SerializeToString,
            ue__service__pb2.StatusResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def ConfigureUE(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ue_service.UEControlService/ConfigureUE',
            ue__service__pb2.ConfigureUERequest.SerializeToString,
            ue__service__pb2.ConfigureUEResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartScanning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ue_service.UEControlService/StartScanning',
            ue__service__pb2.StartScanningRequest.SerializeToString,
            ue__service__pb2.StartScanningResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopScanning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ue_service.UEControlService/StopScanning',
            ue__service__pb2.StopScanningRequest.SerializeToString,
            ue__service__pb2.StopScanningResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class UEDataServiceStub(object):
    """UE Data Acquisition Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StreamCellData = channel.unary_stream(
                '/ue_service.UEDataService/StreamCellData',
                request_serializer=ue__service__pb2.CellDataRequest.SerializeToString,
                response_deserializer=ue__service__pb2.CellDataResponse.FromString,
                _registered_method=True)
        self.StreamLogs = channel.unary_stream(
                '/ue_service.UEDataService/StreamLogs',
                request_serializer=ue__service__pb2.LogRequest.SerializeToString,
                response_deserializer=ue__service__pb2.LogResponse.FromString,
                _registered_method=True)
        self.GetCurrentCells = channel.unary_unary(
                '/ue_service.UEDataService/GetCurrentCells',
                request_serializer=ue__service__pb2.CurrentCellsRequest.SerializeToString,
                response_deserializer=ue__service__pb2.CurrentCellsResponse.FromString,
                _registered_method=True)


class UEDataServiceServicer(object):
    """UE Data Acquisition Service
    """

    def StreamCellData(self, request, context):
        """Stream cell scan data
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLogs(self, request, context):
        """Stream UE logs
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCurrentCells(self, request, context):
        """Get current cell information
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UEDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StreamCellData': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamCellData,
                    request_deserializer=ue__service__pb2.CellDataRequest.FromString,
                    response_serializer=ue__service__pb2.CellDataResponse.SerializeToString,
            ),
            'StreamLogs': grpc.unary_stream_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=ue__service__pb2.LogRequest.FromString,
                    response_serializer=ue__service__pb2.LogResponse.SerializeToString,
            ),
            'GetCurrentCells': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCurrentCells,
                    request_deserializer=ue__service__pb2.CurrentCellsRequest.FromString,
                    response_serializer=ue__service__pb2.CurrentCellsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ue_service.UEDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ue_service.UEDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UEDataService(object):
    """UE Data Acquisition Service
    """

    @staticmethod
    def StreamCellData(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ue_service.UEDataService/StreamCellData',
            ue__service__pb2.CellDataRequest.SerializeToString,
            ue__service__pb2.CellDataResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLogs(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(
            request,
            target,
            '/ue_service.UEDataService/StreamLogs',
            ue__service__pb2.LogRequest.SerializeToString,
            ue__service__pb2.LogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCurrentCells(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ue_service.UEDataService/GetCurrentCells',
            ue__service__pb2.CurrentCellsRequest.SerializeToString,
            ue__service__pb2.CurrentCellsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
