include:
  - docker-compose-base.yaml

services:
    oai-du:
        container_name: "oai-du"
        image: oai-nr-softmodem:ubuntu22
        privileged: true
        ulimits:
          core: -1 # for core dumps
        volumes:
            - ./conf_ran/gnb-du.sa.conf:/opt/oai-gnb/etc/gnb.conf
            - ./startup_scripts/:/startup_scripts/
        networks:
            oai-ran-mplane:
            oai-usrp:
                ipv4_address: 192.168.10.100
        tty: true
        cap_add:
            - NET_ADMIN
        entrypoint: ["bash", "-c", "/startup_scripts/oai-du-x410.sh"]

networks:
    # USRP
    oai-usrp:
        driver: macvlan
        ipam:
            driver: default
            config:
              - subnet: 192.168.10.0/24
        driver_opts:
            parent: ens1f0
