# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import ue_service_pb2 as ue__service__pb2

GRPC_GENERATED_VERSION = '1.74.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in ue_service_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class UEControlServiceStub(object):
    """UE Control Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ConfigureUE = channel.unary_unary(
                '/ue_service.UEControlService/ConfigureUE',
                request_serializer=ue__service__pb2.ConfigureUERequest.SerializeToString,
                response_deserializer=ue__service__pb2.ConfigureUEResponse.FromString,
                _registered_method=True)
        self.StartScanning = channel.unary_unary(
                '/ue_service.UEControlService/StartScanning',
                request_serializer=ue__service__pb2.StartScanningRequest.SerializeToString,
                response_deserializer=ue__service__pb2.StartScanningResponse.FromString,
                _registered_method=True)
        self.StopScanning = channel.unary_unary(
                '/ue_service.UEControlService/StopScanning',
                request_serializer=ue__service__pb2.StopScanningRequest.SerializeToString,
                response_deserializer=ue__service__pb2.StopScanningResponse.FromString,
                _registered_method=True)


class UEControlServiceServicer(object):
    """UE Control Service
    """

    def ConfigureUE(self, request, context):
        """Configure UE parameters
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartScanning(self, request, context):
        """Start cell scanning procedure
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StopScanning(self, request, context):
        """Stop cell scanning procedure
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UEControlServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ConfigureUE': grpc.unary_unary_rpc_method_handler(
                    servicer.ConfigureUE,
                    request_deserializer=ue__service__pb2.ConfigureUERequest.FromString,
                    response_serializer=ue__service__pb2.ConfigureUEResponse.SerializeToString,
            ),
            'StartScanning': grpc.unary_unary_rpc_method_handler(
                    servicer.StartScanning,
                    request_deserializer=ue__service__pb2.StartScanningRequest.FromString,
                    response_serializer=ue__service__pb2.StartScanningResponse.SerializeToString,
            ),
            'StopScanning': grpc.unary_unary_rpc_method_handler(
                    servicer.StopScanning,
                    request_deserializer=ue__service__pb2.StopScanningRequest.FromString,
                    response_serializer=ue__service__pb2.StopScanningResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ue_service.UEControlService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ue_service.UEControlService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UEControlService(object):
    """UE Control Service
    """

    @staticmethod
    def ConfigureUE(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ue_service.UEControlService/ConfigureUE',
            ue__service__pb2.ConfigureUERequest.SerializeToString,
            ue__service__pb2.ConfigureUEResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StartScanning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ue_service.UEControlService/StartScanning',
            ue__service__pb2.StartScanningRequest.SerializeToString,
            ue__service__pb2.StartScanningResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StopScanning(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ue_service.UEControlService/StopScanning',
            ue__service__pb2.StopScanningRequest.SerializeToString,
            ue__service__pb2.StopScanningResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)


class UEDataServiceStub(object):
    """UE Data Acquisition Service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetDetectedCells = channel.unary_unary(
                '/ue_service.UEDataService/GetDetectedCells',
                request_serializer=ue__service__pb2.DetectedCellRequest.SerializeToString,
                response_deserializer=ue__service__pb2.DetectedCellResponse.FromString,
                _registered_method=True)


class UEDataServiceServicer(object):
    """UE Data Acquisition Service
    """

    def GetDetectedCells(self, request, context):
        """Get detected cells
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_UEDataServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetDetectedCells': grpc.unary_unary_rpc_method_handler(
                    servicer.GetDetectedCells,
                    request_deserializer=ue__service__pb2.DetectedCellRequest.FromString,
                    response_serializer=ue__service__pb2.DetectedCellResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ue_service.UEDataService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ue_service.UEDataService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class UEDataService(object):
    """UE Data Acquisition Service
    """

    @staticmethod
    def GetDetectedCells(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ue_service.UEDataService/GetDetectedCells',
            ue__service__pb2.DetectedCellRequest.SerializeToString,
            ue__service__pb2.DetectedCellResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
